<a href="https://colab.research.google.com/github/Nimira43/Artifical-Neural-Network-for-Regression/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.17.0'

#Data Processing

##Import Dataset

In [5]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(dataset)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [7]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#Splitting the dataset into training set and test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#Building the ANN

In [9]:
#Initialising the ANN
ann = tf.keras.models.Sequential()


# Adding the input layer and first hidden layer


In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

In [13]:
print(ann)

<Sequential name=sequential, built=False>


# Training the **ANN**

In [14]:
#Compiling the ANN
ann.compile(optimizer='adam', loss='mean_squared_error')

In [15]:
#Training the ANN model on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 574498.1875
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 46415.4805
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 285.6434
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 240.7758
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 230.6172
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 230.5422
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 228.1915
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 223.1357
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 218.9946
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.7165
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.5069
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 199.6002
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 191.8860
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 183.5249
Epoch 15/1

#Predicting the result from the Test set

In [16]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[431.09 431.23]
 [462.35 460.01]
 [465.94 461.14]
 ...
 [473.   473.26]
 [440.1  438.  ]
 [459.19 463.28]]


# The ANN's predictions are pretty close to the test results